# Generated by Django 3.1.7 on 2021-04-13 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awaygoApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishinorder',
            name='extras',
            field=models.ManyToManyField(null=True, to='awaygoApp.Extra'),
        ),
    ]
