# Generated by Django 3.1.7 on 2021-04-13 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awaygoApp', '0003_auto_20210413_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='dishinorder',
            name='extras',
            field=models.ManyToManyField(blank=True, to='awaygoApp.Extra'),
        ),
    ]
