# Generated by Django 3.1.7 on 2021-04-06 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('awaygoApp', '0005_auto_20210406_0942'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('checkbox', 'Checkbox'), ('radio', 'Radio')], default='checkbox', max_length=9)),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='awaygoApp.dish')),
            ],
            options={
                'verbose_name_plural': 'Extra Categories',
            },
        ),
        migrations.CreateModel(
            name='Extra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('extraCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='awaygoApp.extracategory')),
                ('selectedInDish', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='awaygoApp.dishinorder')),
            ],
        ),
    ]
