# Generated by Django 3.1.7 on 2021-04-20 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awaygoApp', '0005_auto_20210416_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='restaurants/'),
        ),
    ]
