# Generated by Django 3.1.7 on 2021-04-20 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awaygoApp', '0006_restaurant_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='img',
            new_name='background_img',
        ),
    ]
