# Generated by Django 3.1.7 on 2021-04-06 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awaygoApp', '0006_extra_extracategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='dishinorder',
            name='remark',
            field=models.TextField(blank=True, null=True),
        ),
    ]
