# Generated by Django 3.1.7 on 2021-04-06 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awaygoApp', '0007_dishinorder_remark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extra',
            name='selectedInDish',
        ),
        migrations.AddField(
            model_name='dishinorder',
            name='extras',
            field=models.ManyToManyField(to='awaygoApp.Extra'),
        ),
    ]
