# Generated by Django 3.1.7 on 2021-04-23 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awaygoApp', '0008_dish_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='menu_open',
            field=models.BooleanField(default=True),
        ),
    ]
