# Generated by Django 3.1.7 on 2021-04-07 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awaygoApp', '0008_auto_20210406_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='freetext',
            field=models.TextField(blank=True, null=True),
        ),
    ]
