# Generated by Django 3.1.7 on 2021-04-24 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awaygoApp', '0009_restaurant_menu_open'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
