# Generated by Django 3.1.7 on 2021-05-16 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awaygoApp', '0010_dish_visible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='customer',
            name='street',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='order',
            name='number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='street',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
