# Generated by Django 3.1.7 on 2021-06-07 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awaygoApp', '0012_auto_20210522_0928'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='timing_date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='process_date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
