# Generated by Django 3.1.7 on 2021-06-10 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awaygoApp', '0019_auto_20210609_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_distance',
            field=models.DecimalField(decimal_places=3, default=2.3, max_digits=5),
            preserve_default=False,
        ),
    ]
