# Generated by Django 3.1.7 on 2021-06-14 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awaygoApp', '0021_auto_20210614_1618'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='deliveryboy',
        ),
        migrations.DeleteModel(
            name='DeliveryBoy',
        ),
    ]
